// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetServerURL() {
  return window['go']['main']['App']['GetServerURL']();
}

export function OpenInBrowser() {
  return window['go']['main']['App']['OpenInBrowser']();
}
